import { test } from "node:test";
import assert from "node:assert/strict";
import path from "node:path";
import { promoteEvidenceAssets } from "./orvyq_promote_evidence_assets.mjs";
import { projectDir, readJson } from "./lib/fs-utils.mjs";
import { firstReadyProjectId } from "./lib/test-ready-project.mjs";

const PROJECT_ID = firstReadyProjectId();

// Integration test against one discovered ready project's committed manifest.
// assets/evidence/primary_evidence.runtime.json is generated by the evidence
// fetch step and is absent from a fresh source checkout, so declaration alone
// must never promote an asset to ready.
test("promoteEvidenceAssets never promotes an asset with no verified runtime record", async () => {
  const dir = projectDir(PROJECT_ID);
  const manifestPath = path.join(dir, "research", "evidence_asset_manifest.json");
  const before = await readJson(manifestPath);
  const pendingBefore = (before.assets || before.evidence_assets || [])
    .filter((asset) => asset.status === "spec_ready_asset_pending")
    .map((asset) => asset.evidence_asset_id);
  assert.ok(pendingBefore.length > 0, "fixture assumption: a ready project has at least one pending evidence asset");

  const result = await promoteEvidenceAssets(PROJECT_ID);
  assert.deepEqual(result.promoted, [], "no asset should be promoted without a verified runtime record");
  assert.equal(result.stillPending.length, pendingBefore.length);

  const after = await readJson(manifestPath);
  assert.deepEqual(after, before, "the manifest must not be rewritten when nothing was promoted");
});

test("every declared pending asset remains pending when runtime evidence is absent", async () => {
  const dir = projectDir(PROJECT_ID);
  const manifest = await readJson(path.join(dir, "research", "evidence_asset_manifest.json"));
  const expectedIds = new Set(
    (manifest.assets || manifest.evidence_assets || [])
      .filter((asset) => asset.status === "spec_ready_asset_pending")
      .map((asset) => asset.evidence_asset_id),
  );

  const result = await promoteEvidenceAssets(PROJECT_ID);
  const actualIds = new Set(result.stillPending.map((entry) => entry.evidence_asset_id));
  assert.deepEqual(actualIds, expectedIds);
});
